### ISSUE TITLE
Compilation error: exit status 1

### ISSUE THREAD

**Issue by Smart-Stadium** [DatavenueLiveObjects/LiveObjects_SDK_for_Arduino#19]
Hi,

When I try to verify the examples before uploading them to my Arduino MKR WiFi 1010, I have this error message.

I use Arduino 2.0.3.

I followed the prerequesites. Do you have an idea to fix my issue ?

Regards
[arduino_error_message.txt](https://github.com/DatavenueLiveObjects/LiveObjects_SDK_for_Arduino/files/10757247/arduino_error_message.txt)

**Comment by tomekmalek** [comment]
Hi,

This issue is connected to the newest version (6.20.0) of ArduinoJson library. If you downgrade it to the previous one (6.19.4) it should help.

Best regards
Tomasz

**Comment by Smart-Stadium** [comment]
Hi,

It works. Do you plan to make ArduinoJson compatible with new versions (6.21)?

Regards
